/**
 * CampusLink MVP — Map Types
 *
 * Central type definitions for the 3D campus map interaction.
 * These types match the node names from the GLB model generated by gltfjsx.
 *
 * UPDATED: Cabins are now 3 separate buildings (cabin01, cabin02, cabin03).
 */

/** Identifiers for each building in the campus model */
export type BuildingId =
  | 'ebuilding'
  | 'cabin01'
  | 'cabin02'
  | 'cabin03'
  | 'hbuilding'
  | 'cti'
  | 'gym';

/** Definition of a single floor within a building */
export interface FloorDefinition {
  /** Unique identifier, e.g. 'ebuilding-floor-1' */
  id: string;
  /** Parent building */
  buildingId: BuildingId;
  /** Floor level number (1-indexed) */
  level: number;
  /** Floor group name in the GLB model, e.g. 'ebuilding_floor1' */
  meshName: string;
  /** Human-readable display name */
  name: string;
  /** Description shown in the modal */
  description: string;
}

/** Configuration for a building's camera focus and floor list */
export interface BuildingConfig {
  id: BuildingId;
  /** Human-readable building name */
  name: string;
  /** List of floor group names for each floor */
  floors: string[];
  /** Camera target position [x, y, z] when building is selected */
  focusTarget: [number, number, number];
  /** Camera position [x, y, z] when zoomed into building */
  focusPosition: [number, number, number];
}

/** Configuration for a single floor group (multi-mesh floor) */
export interface FloorMeshConfig {
  /** Floor identifier, e.g. 'ebuilding_floor1' */
  meshName: string;
  /** Parent building */
  buildingId: BuildingId;
  /** Original position from the GLB model [x, y, z] */
  position: [number, number, number];
  /** Node names of the sub-meshes that compose this floor */
  subMeshes: string[];
}

/** Zustand store state shape */
export interface MapState {
  selectedBuilding: BuildingId | null;
  selectedFloor: string | null;
  isExploded: boolean;
  isFloorModalOpen: boolean;

  selectBuilding: (buildingId: BuildingId) => void;
  selectFloor: (floorId: string) => void;
  closeFloorModal: () => void;
  resetBuilding: () => void;
}
