// Generated by npm run poi:images. Add photos in assets/images/poimages, not here.
import type { ImageSourcePropType } from 'react-native';

export const POI_IMAGES: Readonly<Record<string, ImageSourcePropType>> = {
  ["cabin01-sala-reuniones-interior.jpg"]: require("../../../assets/images/poimages/cabin01-sala-reuniones-interior.jpg"),
  ["cabin01-sala-reuniones.jpg"]: require("../../../assets/images/poimages/cabin01-sala-reuniones.jpg"),
  ["cabin03-floor2-ciit.jpg"]: require("../../../assets/images/poimages/cabin03-floor2-ciit.jpg"),
  ["cabin03-floor3-punto-estudiantil.jpg"]: require("../../../assets/images/poimages/cabin03-floor3-punto-estudiantil.jpg"),
  ["cabin03-floor3-radio.jpg"]: require("../../../assets/images/poimages/cabin03-floor3-radio.jpg"),
  ["ebuilding-floor1-caja-de-pago.jpg"]: require("../../../assets/images/poimages/ebuilding-floor1-caja-de-pago.jpg"),
  ["fbuilding-floor1-capilla.jpg"]: require("../../../assets/images/poimages/fbuilding-floor1-capilla.jpg"),
  ["fbuilding-floor2-casino.jpg"]: require("../../../assets/images/poimages/fbuilding-floor2-casino.jpg"),
  ["fbuilding-floor3-central-de-apuntes.jpg"]: require("../../../assets/images/poimages/fbuilding-floor3-central-de-apuntes.jpg"),
  ["fbuilding-floor3-cetecom.jpg"]: require("../../../assets/images/poimages/fbuilding-floor3-cetecom.jpg"),
  ["fbuilding-floor4-terraza.jpg"]: require("../../../assets/images/poimages/fbuilding-floor4-terraza.jpg"),
  ["gym-floor1-multicancha.jpg"]: require("../../../assets/images/poimages/gym-floor1-multicancha.jpg"),
  ["gym-floor1-sala-de-musculacion.jpg"]: require("../../../assets/images/poimages/gym-floor1-sala-de-musculacion.jpg"),
  ["hbuilding-floor1-auditorio.jpg"]: require("../../../assets/images/poimages/hbuilding-floor1-auditorio.jpg"),
  ["hbuilding-floor1-casino.jpg"]: require("../../../assets/images/poimages/hbuilding-floor1-casino.jpg"),
  ["hbuilding-floor2-biblioteca.jpg"]: require("../../../assets/images/poimages/hbuilding-floor2-biblioteca.jpg"),
  ["hbuilding-floor4-cetecom.jpg"]: require("../../../assets/images/poimages/hbuilding-floor4-cetecom.jpg"),
};
